//! Single-include amalgamation header(s).
//!
//! For internal cheats it's enormously useful to have one file you can
//! `#include` (or one Rust module you can copy in) that pulls in
//! offsets + interfaces + netvars + signatures + the SDK macros all at
//! once.
//!
//! This module emits:
//!
//! - `cs2sdk.hpp` — single-include C++ amalgamation
//! - `cs2sdk.rs`  — single-file Rust module
//!
//! Both are *idempotent* — they only re-export what other emitters in
//! this run produced, they don't duplicate any data.
//!
//! ## Design choice: `#include`s vs amalgamation
//!
//! We deliberately use `#include` rather than concatenating every file's
//! contents into one mega-file. That keeps:
//!
//! 1. compile times low (the user only pays for what they touch),
//! 2. error messages pointing at the right file, and
//! 3. diffs between two builds clean.

/// Render a single-include C++ header.
///
/// `sdk_modules` is the list of module file stems that the SDK class
/// emitter wrote (e.g. `["client_dll", "engine2_dll"]`).
pub fn render_hpp(sdk_modules: &[String], build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("//\n");
    s.push_str("// Single-include amalgamation header for CS2 internal cheats.\n");
    s.push_str("//\n");
    s.push_str("// Drop the `sdk/` and `signatures/` folders into your project\n");
    s.push_str("// (preserving their relative layout), add `sdk/` to your\n");
    s.push_str("// include path, and:\n");
    s.push_str("//\n");
    s.push_str("//     #include \"cs2sdk.hpp\"\n");
    s.push_str("//\n");
    s.push_str("// gets you typed schema classes, netvars, interface accessors,\n");
    s.push_str("// and pattern strings for every resolved signature.\n\n");
    s.push_str("#pragma once\n\n");
    if let Some(bn) = build_number {
        s.push_str(&format!(
            "inline constexpr unsigned int CS2_BUILD = {bn};\n\n"
        ));
    }
    s.push_str("// SDK macros (SCHEMA_FIELD, field_ref<T>, ...)\n");
    s.push_str("#include \"cs2sdk_macros.hpp\"\n\n");
    s.push_str("// Per-module schema classes\n");
    // Attempt to read a module ordering file emitted by the SDK class
    // emitter so the single-include amalgamation preserves the same
    // include ordering. Fallback to the input order if not present.
    let mut ordered_modules: Vec<String> = sdk_modules.to_vec();
    let order_path_candidates = ["include/sdk/module_order.txt", "module_order.txt"];
    for p in &order_path_candidates {
        if let Ok(txt) = std::fs::read_to_string(p) {
            let mut order_map: std::collections::BTreeMap<usize, String> =
                std::collections::BTreeMap::new();
            for line in txt.lines() {
                if let Some((idxs, name)) = line.split_once(':') {
                    if let Ok(idx) = idxs.parse::<usize>() {
                        order_map.insert(idx, name.to_string());
                    }
                }
            }
            if !order_map.is_empty() {
                // Build mapping from module stem -> index for sorting
                let mut idx_map: std::collections::BTreeMap<String, usize> =
                    std::collections::BTreeMap::new();
                for (i, name) in order_map.into_iter() {
                    // strip any .dll suffixes and _dll variants
                    let stem = name.trim().trim_end_matches(".dll").to_string();
                    idx_map.insert(stem, i);
                }
                ordered_modules.sort_by_key(|m| idx_map.get(m).cloned().unwrap_or(usize::MAX));
                break;
            }
        }
    }

    // Ensure client comes before server in the amalgamation to avoid
    // base-class undefined errors for client-owned bases used by server.
    if ordered_modules.contains(&"server_dll".to_string())
        && ordered_modules.contains(&"client_dll".to_string())
    {
        ordered_modules.retain(|m| m != "client_dll");
        // place client_dll just before server_dll
        if let Some(pos) = ordered_modules.iter().position(|m| m == "server_dll") {
            ordered_modules.insert(pos, "client_dll".to_string());
        } else {
            ordered_modules.insert(0, "client_dll".to_string());
        }
    }

    for m in ordered_modules {
        s.push_str(&format!("#include \"{}.hpp\"\n", m));
    }
    s.push('\n');
    s.push_str("// Typed accessors + signature patterns\n");
    s.push_str("// (netvars.hpp is optional — include it yourself if your project needs it)\n");
    s.push_str("#include \"interfaces_sdk.hpp\"\n");
    s.push_str("#include \"../signatures/signatures.hpp\"\n");
    s
}

/// Render a single-file Rust module that re-exports every emitted
/// `*.rs` consumer file.
pub fn render_rs(sig_modules_present: bool, build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("//\n");
    s.push_str("// Single-file Rust amalgamation. Drop the session's `sdk/` and\n");
    s.push_str("// `signatures/` directories side-by-side and add `mod cs2sdk;`\n");
    s.push_str("// pointing at this file.\n\n");
    s.push_str("#![allow(non_upper_case_globals, non_snake_case, dead_code)]\n\n");
    if let Some(bn) = build_number {
        s.push_str(&format!("pub const CS2_BUILD: u32 = {bn};\n\n"));
    }
    if sig_modules_present {
        s.push_str("#[path = \"../signatures/signatures.rs\"] pub mod signatures;\n");
    }
    s
}
