use std::fs;
use std::path::Path;
use anyhow::Result;
use crate::analysis::AnalysisResult;

pub fn generate(out_dir: &Path, analysis: &AnalysisResult) -> Result<()> {
    let mut s = String::new();
    s.push_str("# CS2 SDK Integration Guide for AI Models\n\n");
    s.push_str("## Context\n");
    s.push_str("This directory contains a full-engine SDK for Counter-Strike 2, generated by walking the memory of a live process. It includes class layouts, interface offsets, and instruction signatures.\n\n");

    s.push_str("## Core Components\n");
    s.push_str("- **Class Hierarchy**: See `hierarchy.html` for a visual map of how engine classes relate.\n");
    s.push_str("- **Memory Layouts**: Use `xsip_sdk/` headers. They use `S2_PAD` for exact byte-alignment. Pointers are 64-bit.\n");
    s.push_str("- **Accessor Macros**: `sdk/cs2sdk_macros.hpp` provides `SCHEMA_FIELD` which is preferred for internal cheats.\n");
    s.push_str("- **Interfaces**: `xsip_interfaces/` contains offsets for `CreateInterface` targets. Use these to get singleton pointers.\n");
    s.push_str("- **Signatures**: `signatures/signatures.json` provides IDA-style patterns for functions. Use these to find logic that isn't in schemas.\n\n");

    s.push_str("## Common AI Tasks\n");
    s.push_str("1. **Find a field**: Search for the field name (e.g., `m_iHealth`) in `xsip_sdk/`. Note the offset and the class size.\n");
    s.push_str("2. **Calculate a Pointer**: To find the local player, look up `dwLocalPlayerController` in `sdk/offsets.json`, read the controller, then follow `m_hPawn` to the pawn.\n");
    s.push_str("3. **Hook a function**: Find the function name in `signatures/signatures.hpp`. Use the provided typedef and the `rva` to set up your hook.\n");
    s.push_str("4. **Analyze an event**: Check `report.json` or `report.html` under the `game_events` section to see which fields are available in events like `player_death`.\n\n");

    s.push_str("## Engine Metadata\n");
    s.push_str(&format!("- Total classes discovered: {}\n", analysis.schemas.values().map(|(c, _)| c.len()).sum::<usize>()));
    s.push_str(&format!("- Total interfaces discovered: {}\n", analysis.interfaces.values().map(|i| i.len()).sum::<usize>()));
    s.push_str(&format!("- Total ConVars extracted: {}\n", analysis.convars.len()));

    fs::write(out_dir.join("llm.txt"), s)?;
    Ok(())
}
