use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::Result;
use crate::analysis::{Class, Enum, SchemaMap};
use super::ident::slugify;

use crate::ui;

pub fn dump(
    out_dir: &Path,
    schemas: &SchemaMap,
) -> Result<()> {
    let xsip_sdk_dir = out_dir.join("xsip_sdk");
    fs::create_dir_all(&xsip_sdk_dir)?;

    write_global_types(&xsip_sdk_dir)?;

    let type_to_module = build_type_to_module_map(schemas);

    let total_modules = schemas.len();
    for (i, (module_name, (classes, enums))) in schemas.iter().enumerate() {
        ui::progress(i, total_modules, &format!("dumping xsip-sdk: {}", module_name));
        let module_slug = slugify(module_name.trim_end_matches(".dll"));
        let module_dir = xsip_sdk_dir.join(&module_slug);
        fs::create_dir_all(&module_dir)?;

        for class in classes {
            write_class_header(&module_dir, &module_slug, class, &type_to_module)?;
        }

        for enm in enums {
            write_enum_header(&module_dir, &module_slug, enm)?;
        }
    }

    ui::progress(total_modules, total_modules, "dumping xsip-sdk: done");
    println!();
    Ok(())
}

fn build_type_to_module_map(schemas: &SchemaMap) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    for (module_name, (classes, enums)) in schemas {
        let module_slug = slugify(module_name.trim_end_matches(".dll"));
        for class in classes {
            map.insert(class.name.clone(), module_slug.clone());
        }
        for enm in enums {
            map.insert(enm.name.clone(), module_slug.clone());
        }
    }
    map
}

fn write_global_types(dir: &Path) -> Result<()> {
    let content = r#"#pragma once

#include <cstdint>
#include <cstddef>

namespace GlobalTypes {
    template <typename T>
    struct CHandle {
        uint32_t m_Index;
    };

    template <typename T>
    struct CUtlVector {
        T* m_pElements;
        int m_Size;
        int m_Capacity;
    };

    struct CSplitScreenSlot {
        int m_nSlot;
    };
}

#define S2_PAD(size) char pad_##__LINE__[size]
"#;
    fs::write(dir.join("GlobalTypes.hpp"), content)?;
    Ok(())
}

fn write_class_header(
    module_dir: &Path,
    module_slug: &str,
    class: &Class,
    type_to_module: &BTreeMap<String, String>,
) -> Result<()> {
    let mut s = String::new();
    writeln!(s, "// generated - do not edit!")?;
    writeln!(s, "// generated by cs2-sdk expanded dumper")?;
    writeln!(s)?;
    writeln!(s, "#pragma once")?;
    writeln!(s)?;
    writeln!(s, "#ifndef CUSTOM_GLOBAL_TYPES")?;
    writeln!(s, "    #include \"../GlobalTypes.hpp\"")?;
    writeln!(s, "#else")?;
    writeln!(s, "    #include <Custom/GlobalTypes.hpp>")?;
    writeln!(s, "#endif")?;
    writeln!(s)?;

    let mut includes = BTreeSet::new();
    if let Some(parent) = &class.parent_name {
        if let Some(module) = type_to_module.get(parent) {
            if module == module_slug {
                includes.insert(format!("{}.hpp", parent));
            } else {
                writeln!(s, "#include \"../../{}/{}.hpp\"", module, parent)?;
            }
        }
    }

    // Heuristic for field types that need includes
    for field in &class.fields {
        let clean_type = field.type_name.split('<').next().unwrap().split('[').next().unwrap();
        if let Some(module) = type_to_module.get(clean_type) {
            if module == module_slug && clean_type != &class.name {
                includes.insert(format!("{}.hpp", clean_type));
            }
        }
    }

    for inc in includes {
        writeln!(s, "#include \"{}\"", inc)?;
    }

    writeln!(s)?;
    // Forward declarations
    let mut forward_decls = BTreeMap::new();
    for field in &class.fields {
        let clean_type = field.type_name.split('<').next().unwrap().split('[').next().unwrap();
        if let Some(module) = type_to_module.get(clean_type) {
            forward_decls.entry(module.clone()).or_insert_with(BTreeSet::new).insert(clean_type.to_string());
        }
    }
    if let Some(parent) = &class.parent_name {
        if let Some(module) = type_to_module.get(parent) {
            forward_decls.entry(module.clone()).or_insert_with(BTreeSet::new).insert(parent.to_string());
        }
    }

    for (module, types) in forward_decls {
        writeln!(s, "namespace CS2 {{")?;
        writeln!(s, "    namespace {} {{", module)?;
        for ty in types {
            if ty != class.name {
                writeln!(s, "        class {};", ty)?;
            }
        }
        writeln!(s, "    }}")?;
        writeln!(s, "}}")?;
    }

    writeln!(s)?;
    writeln!(s, "using namespace GlobalTypes;")?;
    writeln!(s, "namespace CS2 {{")?;
    writeln!(s, "    namespace {} {{", module_slug)?;

    let parent_str = if let Some(parent) = &class.parent_name {
        let parent_module = type_to_module.get(parent).map(|s| s.as_str()).unwrap_or(module_slug);
        format!(" : public CS2::{}::{}", parent_module, parent)
    } else {
        "".to_string()
    };

    writeln!(s, "        class {}{} {{", class.name, parent_str)?;
    writeln!(s, "        public:")?;

    let mut current_offset = 0;
    // We assume fields are sorted by offset
    let mut sorted_fields = class.fields.clone();
    sorted_fields.sort_by_key(|f| f.offset);

    for field in sorted_fields {
        if field.offset > current_offset {
            writeln!(s, "            S2_PAD({:#X});", field.offset - current_offset)?;
        } else if field.offset < current_offset {
             writeln!(s, "            // WARNING: field {} at {:#X} overlaps with previous field!", field.name, field.offset)?;
        }

        let cpp_type = map_type(&field.type_name, module_slug, type_to_module);
        writeln!(s, "            {} {}; // {:#X} | Size: {:#X}", cpp_type, field.name, field.offset, field.size)?;

        current_offset = field.offset + field.size;
    }

    if (class.size as i32) > current_offset {
        writeln!(s, "            S2_PAD({:#X}); // End padding", class.size - current_offset)?;
    }

    writeln!(s, "        }};")?;

    writeln!(s, "#ifdef USE_STATIC_ASSERTS")?;
    for field in &class.fields {
        writeln!(s, "        static_assert(offsetof(CS2::{}::{}, {}) == {:#X}, \"{} in {} should be at offset {:#X}\");",
            module_slug, class.name, field.name, field.offset, field.name, class.name, field.offset)?;
    }
    writeln!(s, "        static_assert(sizeof(CS2::{}::{}) == {:#X}, \"{} size should be {:#X}\");",
        module_slug, class.name, class.size, class.name, class.size)?;
    writeln!(s, "#endif")?;

    writeln!(s, "    }}")?;
    writeln!(s)?;
    writeln!(s, "}}")?;

    fs::write(module_dir.join(format!("{}.hpp", class.name)), s)?;
    Ok(())
}

fn write_enum_header(
    module_dir: &Path,
    module_slug: &str,
    enm: &Enum,
) -> Result<()> {
    let mut s = String::new();
    writeln!(s, "// generated - do not edit!")?;
    writeln!(s, "#pragma once")?;
    writeln!(s)?;
    writeln!(s, "#include <cstdint>")?;
    writeln!(s)?;
    writeln!(s, "namespace CS2 {{")?;
    writeln!(s, "    namespace {} {{", module_slug)?;

    let underlying = match enm.alignment {
        1 => "uint8_t",
        2 => "uint16_t",
        4 => "uint32_t",
        8 => "uint64_t",
        _ => "uint32_t",
    };

    writeln!(s, "        enum class {} : {} {{", enm.name, underlying)?;
    for member in &enm.members {
        writeln!(s, "            {} = {:#X},", member.name, member.value)?;
    }
    writeln!(s, "        }};")?;
    writeln!(s, "    }}")?;
    writeln!(s, "}}")?;

    fs::write(module_dir.join(format!("{}.hpp", enm.name)), s)?;
    Ok(())
}

fn map_type(raw: &str, current_module: &str, type_to_module: &BTreeMap<String, String>) -> String {
    if raw.starts_with("CHandle<") {
        let inner = &raw[8..raw.len()-1].trim();
        let mapped_inner = map_type(inner, current_module, type_to_module);
        return format!("GlobalTypes::CHandle<{}>", mapped_inner);
    }
    if raw.starts_with("CUtlVector<") {
        let inner = &raw[11..raw.len()-1].trim();
        let mapped_inner = map_type(inner, current_module, type_to_module);
        return format!("GlobalTypes::CUtlVector<{}>", mapped_inner);
    }

    let base_type = match raw {
        "int32" => "int32_t".into(),
        "uint32" => "uint32_t".into(),
        "int16" => "int16_t".into(),
        "uint16" => "uint16_t".into(),
        "int8" => "int8_t".into(),
        "uint8" => "uint8_t".into(),
        "int64" => "int64_t".into(),
        "uint64" => "uint64_t".into(),
        "float32" => "float".into(),
        "float64" => "double".into(),
        "bool" => "bool".into(),
        _ => {
            if let Some(module) = type_to_module.get(raw) {
                format!("{}::{}", module, raw)
            } else {
                raw.to_string()
            }
        }
    };
    base_type
}
